/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AktivitaetAnzeige
 */
public class AktivitaetAnzeigeTest {
    private final AktivitaetAnzeige model = new AktivitaetAnzeige();

    /**
     * Model tests for AktivitaetAnzeige
     */
    @Test
    public void testAktivitaetAnzeige() {
        // TODO: test AktivitaetAnzeige
    }

    /**
     * Test the property 'aktivitaetsart'
     */
    @Test
    public void aktivitaetsartTest() {
        // TODO: test aktivitaetsart
    }

    /**
     * Test the property 'titel'
     */
    @Test
    public void titelTest() {
        // TODO: test titel
    }

    /**
     * Test the property 'pdfUrl'
     */
    @Test
    public void pdfUrlTest() {
        // TODO: test pdfUrl
    }

    /**
     * Test the property 'seite'
     */
    @Test
    public void seiteTest() {
        // TODO: test seite
    }

}
