/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Beschlussfassung
 */
public class BeschlussfassungTest {
    private final Beschlussfassung model = new Beschlussfassung();

    /**
     * Model tests for Beschlussfassung
     */
    @Test
    public void testBeschlussfassung() {
        // TODO: test Beschlussfassung
    }

    /**
     * Test the property 'beschlusstenor'
     */
    @Test
    public void beschlusstenorTest() {
        // TODO: test beschlusstenor
    }

    /**
     * Test the property 'seite'
     */
    @Test
    public void seiteTest() {
        // TODO: test seite
    }

    /**
     * Test the property 'abstimmungsart'
     */
    @Test
    public void abstimmungsartTest() {
        // TODO: test abstimmungsart
    }

    /**
     * Test the property 'abstimmErgebnisBemerkung'
     */
    @Test
    public void abstimmErgebnisBemerkungTest() {
        // TODO: test abstimmErgebnisBemerkung
    }

    /**
     * Test the property 'grundlage'
     */
    @Test
    public void grundlageTest() {
        // TODO: test grundlage
    }

    /**
     * Test the property 'dokumentnummer'
     */
    @Test
    public void dokumentnummerTest() {
        // TODO: test dokumentnummer
    }

    /**
     * Test the property 'mehrheit'
     */
    @Test
    public void mehrheitTest() {
        // TODO: test mehrheit
    }

}
