/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DrucksacheAutorenAnzeigeInner
 */
public class DrucksacheAutorenAnzeigeInnerTest {
    private final DrucksacheAutorenAnzeigeInner model = new DrucksacheAutorenAnzeigeInner();

    /**
     * Model tests for DrucksacheAutorenAnzeigeInner
     */
    @Test
    public void testDrucksacheAutorenAnzeigeInner() {
        // TODO: test DrucksacheAutorenAnzeigeInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'autorTitel'
     */
    @Test
    public void autorTitelTest() {
        // TODO: test autorTitel
    }

}
