/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Bundesland;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PersonRole
 */
public class PersonRoleTest {
    private final PersonRole model = new PersonRole();

    /**
     * Model tests for PersonRole
     */
    @Test
    public void testPersonRole() {
        // TODO: test PersonRole
    }

    /**
     * Test the property 'funktion'
     */
    @Test
    public void funktionTest() {
        // TODO: test funktion
    }

    /**
     * Test the property 'funktionszusatz'
     */
    @Test
    public void funktionszusatzTest() {
        // TODO: test funktionszusatz
    }

    /**
     * Test the property 'fraktion'
     */
    @Test
    public void fraktionTest() {
        // TODO: test fraktion
    }

    /**
     * Test the property 'nachname'
     */
    @Test
    public void nachnameTest() {
        // TODO: test nachname
    }

    /**
     * Test the property 'vorname'
     */
    @Test
    public void vornameTest() {
        // TODO: test vorname
    }

    /**
     * Test the property 'namenszusatz'
     */
    @Test
    public void namenszusatzTest() {
        // TODO: test namenszusatz
    }

    /**
     * Test the property 'wahlperiodeNummer'
     */
    @Test
    public void wahlperiodeNummerTest() {
        // TODO: test wahlperiodeNummer
    }

    /**
     * Test the property 'wahlkreiszusatz'
     */
    @Test
    public void wahlkreiszusatzTest() {
        // TODO: test wahlkreiszusatz
    }

    /**
     * Test the property 'ressortTitel'
     */
    @Test
    public void ressortTitelTest() {
        // TODO: test ressortTitel
    }

    /**
     * Test the property 'bundesland'
     */
    @Test
    public void bundeslandTest() {
        // TODO: test bundesland
    }

}
