/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Fundstelle;
import org.openapitools.client.model.Vorgangsbezug;
import org.openapitools.client.model.Zuordnung;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Plenarprotokoll
 */
public class PlenarprotokollTest {
    private final Plenarprotokoll model = new Plenarprotokoll();

    /**
     * Model tests for Plenarprotokoll
     */
    @Test
    public void testPlenarprotokoll() {
        // TODO: test Plenarprotokoll
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dokumentart'
     */
    @Test
    public void dokumentartTest() {
        // TODO: test dokumentart
    }

    /**
     * Test the property 'typ'
     */
    @Test
    public void typTest() {
        // TODO: test typ
    }

    /**
     * Test the property 'dokumentnummer'
     */
    @Test
    public void dokumentnummerTest() {
        // TODO: test dokumentnummer
    }

    /**
     * Test the property 'wahlperiode'
     */
    @Test
    public void wahlperiodeTest() {
        // TODO: test wahlperiode
    }

    /**
     * Test the property 'herausgeber'
     */
    @Test
    public void herausgeberTest() {
        // TODO: test herausgeber
    }

    /**
     * Test the property 'datum'
     */
    @Test
    public void datumTest() {
        // TODO: test datum
    }

    /**
     * Test the property 'aktualisiert'
     */
    @Test
    public void aktualisiertTest() {
        // TODO: test aktualisiert
    }

    /**
     * Test the property 'titel'
     */
    @Test
    public void titelTest() {
        // TODO: test titel
    }

    /**
     * Test the property 'fundstelle'
     */
    @Test
    public void fundstelleTest() {
        // TODO: test fundstelle
    }

    /**
     * Test the property 'pdfHash'
     */
    @Test
    public void pdfHashTest() {
        // TODO: test pdfHash
    }

    /**
     * Test the property 'vorgangsbezug'
     */
    @Test
    public void vorgangsbezugTest() {
        // TODO: test vorgangsbezug
    }

    /**
     * Test the property 'vorgangsbezugAnzahl'
     */
    @Test
    public void vorgangsbezugAnzahlTest() {
        // TODO: test vorgangsbezugAnzahl
    }

    /**
     * Test the property 'sitzungsbemerkung'
     */
    @Test
    public void sitzungsbemerkungTest() {
        // TODO: test sitzungsbemerkung
    }

}
