/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Plenarprotokoll;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlenarprotokollListResponse
 */
public class PlenarprotokollListResponseTest {
    private final PlenarprotokollListResponse model = new PlenarprotokollListResponse();

    /**
     * Model tests for PlenarprotokollListResponse
     */
    @Test
    public void testPlenarprotokollListResponse() {
        // TODO: test PlenarprotokollListResponse
    }

    /**
     * Test the property 'numFound'
     */
    @Test
    public void numFoundTest() {
        // TODO: test numFound
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

}
