/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Urheber
 */
public class UrheberTest {
    private final Urheber model = new Urheber();

    /**
     * Model tests for Urheber
     */
    @Test
    public void testUrheber() {
        // TODO: test Urheber
    }

    /**
     * Test the property 'einbringer'
     */
    @Test
    public void einbringerTest() {
        // TODO: test einbringer
    }

    /**
     * Test the property 'bezeichnung'
     */
    @Test
    public void bezeichnungTest() {
        // TODO: test bezeichnung
    }

    /**
     * Test the property 'titel'
     */
    @Test
    public void titelTest() {
        // TODO: test titel
    }

    /**
     * Test the property 'rolle'
     */
    @Test
    public void rolleTest() {
        // TODO: test rolle
    }

}
