/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Vorgangspositionbezug
 */
public class VorgangspositionbezugTest {
    private final Vorgangspositionbezug model = new Vorgangspositionbezug();

    /**
     * Model tests for Vorgangspositionbezug
     */
    @Test
    public void testVorgangspositionbezug() {
        // TODO: test Vorgangspositionbezug
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'titel'
     */
    @Test
    public void titelTest() {
        // TODO: test titel
    }

    /**
     * Test the property 'vorgangstyp'
     */
    @Test
    public void vorgangstypTest() {
        // TODO: test vorgangstyp
    }

    /**
     * Test the property 'vorgangsposition'
     */
    @Test
    public void vorgangspositionTest() {
        // TODO: test vorgangsposition
    }

}
