/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VorgangDeskriptor
 */
public class VorgangDeskriptorTest {
    private final VorgangDeskriptor model = new VorgangDeskriptor();

    /**
     * Model tests for VorgangDeskriptor
     */
    @Test
    public void testVorgangDeskriptor() {
        // TODO: test VorgangDeskriptor
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'typ'
     */
    @Test
    public void typTest() {
        // TODO: test typ
    }

    /**
     * Test the property 'fundstelle'
     */
    @Test
    public void fundstelleTest() {
        // TODO: test fundstelle
    }

}
