/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetVorgang404Response;
import org.openapitools.client.model.GetVorgangList400Response;
import org.openapitools.client.model.GetVorgangList401Response;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Person;
import org.openapitools.client.model.PersonListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PersonenstammdatenApi
 */
@Disabled
public class PersonenstammdatenApiTest {

    private final PersonenstammdatenApi api = new PersonenstammdatenApi();

    /**
     * Liefert Personenstammdaten zu einer Person
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPersonTest() throws ApiException {
        Integer id = null;
        String format = null;
        Person response = api.getPerson(id, format);
        // TODO: test validations
    }

    /**
     * Liefert eine Liste von Personenstammdaten
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPersonListTest() throws ApiException {
        OffsetDateTime fAktualisiertStart = null;
        OffsetDateTime fAktualisiertEnd = null;
        LocalDate fDatumStart = null;
        LocalDate fDatumEnd = null;
        List<Integer> fId = null;
        List<Integer> fWahlperiode = null;
        String cursor = null;
        String format = null;
        PersonListResponse response = api.getPersonList(fAktualisiertStart, fAktualisiertEnd, fDatumStart, fDatumEnd, fId, fWahlperiode, cursor, format);
        // TODO: test validations
    }

}
