/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetVorgang404Response;
import org.openapitools.client.model.GetVorgangList400Response;
import org.openapitools.client.model.GetVorgangList401Response;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Plenarprotokoll;
import org.openapitools.client.model.PlenarprotokollListResponse;
import org.openapitools.client.model.PlenarprotokollText;
import org.openapitools.client.model.PlenarprotokollTextListResponse;
import org.openapitools.client.model.Zuordnung;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlenarprotokolleApi
 */
@Disabled
public class PlenarprotokolleApiTest {

    private final PlenarprotokolleApi api = new PlenarprotokolleApi();

    /**
     * Liefert Metadaten zu einem Plenarprotokoll
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlenarprotokollTest() throws ApiException {
        Integer id = null;
        String format = null;
        Plenarprotokoll response = api.getPlenarprotokoll(id, format);
        // TODO: test validations
    }

    /**
     * Liefert eine Liste von Metadaten zu Plenarprotokollen
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlenarprotokollListTest() throws ApiException {
        OffsetDateTime fAktualisiertStart = null;
        OffsetDateTime fAktualisiertEnd = null;
        LocalDate fDatumStart = null;
        LocalDate fDatumEnd = null;
        List<String> fDokumentnummer = null;
        List<Integer> fId = null;
        List<String> fVorgangstyp = null;
        List<Integer> fVorgangstypNotation = null;
        List<Integer> fWahlperiode = null;
        Zuordnung fZuordnung = null;
        String cursor = null;
        String format = null;
        PlenarprotokollListResponse response = api.getPlenarprotokollList(fAktualisiertStart, fAktualisiertEnd, fDatumStart, fDatumEnd, fDokumentnummer, fId, fVorgangstyp, fVorgangstypNotation, fWahlperiode, fZuordnung, cursor, format);
        // TODO: test validations
    }

    /**
     * Liefert Volltext und Metadaten zu einem Plenarprotokoll
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlenarprotokollTextTest() throws ApiException {
        Integer id = null;
        String format = null;
        PlenarprotokollText response = api.getPlenarprotokollText(id, format);
        // TODO: test validations
    }

    /**
     * Liefert eine Liste von Volltexten und Metadaten zu Plenarprotokollen
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlenarprotokollTextListTest() throws ApiException {
        OffsetDateTime fAktualisiertStart = null;
        OffsetDateTime fAktualisiertEnd = null;
        LocalDate fDatumStart = null;
        LocalDate fDatumEnd = null;
        List<String> fDokumentnummer = null;
        List<Integer> fId = null;
        List<String> fVorgangstyp = null;
        List<Integer> fVorgangstypNotation = null;
        List<Integer> fWahlperiode = null;
        Zuordnung fZuordnung = null;
        String cursor = null;
        String format = null;
        PlenarprotokollTextListResponse response = api.getPlenarprotokollTextList(fAktualisiertStart, fAktualisiertEnd, fDatumStart, fDatumEnd, fDokumentnummer, fId, fVorgangstyp, fVorgangstypNotation, fWahlperiode, fZuordnung, cursor, format);
        // TODO: test validations
    }

}
