/*
 * Deutscher Bundestag - DIP
 * API des Dokumentations- und Informationssystems für Parlamentsmaterialien
 *
 * The version of the OpenAPI document: 1.3
 * Contact: parlamentsdokumentation@bundestag.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GetVorgang404Response;
import org.openapitools.client.model.GetVorgangList400Response;
import org.openapitools.client.model.GetVorgangList401Response;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Vorgangsposition;
import org.openapitools.client.model.VorgangspositionListResponse;
import org.openapitools.client.model.Zuordnung;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VorgangspositionenApi
 */
@Disabled
public class VorgangspositionenApiTest {

    private final VorgangspositionenApi api = new VorgangspositionenApi();

    /**
     * Liefert Metadaten zu einer Vorgangsposition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVorgangspositionTest() throws ApiException {
        Integer id = null;
        String format = null;
        Vorgangsposition response = api.getVorgangsposition(id, format);
        // TODO: test validations
    }

    /**
     * Liefert eine Liste von Metadaten zu Vorgangspositionen
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVorgangspositionListTest() throws ApiException {
        Integer fAktivitaet = null;
        OffsetDateTime fAktualisiertStart = null;
        OffsetDateTime fAktualisiertEnd = null;
        LocalDate fDatumStart = null;
        LocalDate fDatumEnd = null;
        String fDokumentart = null;
        List<String> fDokumentnummer = null;
        Integer fDrucksache = null;
        String fDrucksachetyp = null;
        List<String> fFrageNummer = null;
        List<Integer> fId = null;
        Integer fPlenarprotokoll = null;
        List<String> fRessortFdf = null;
        List<String> fTitel = null;
        List<String> fUrheber = null;
        Integer fVorgang = null;
        List<String> fVorgangstyp = null;
        List<Integer> fVorgangstypNotation = null;
        List<Integer> fWahlperiode = null;
        Zuordnung fZuordnung = null;
        String cursor = null;
        String format = null;
        VorgangspositionListResponse response = api.getVorgangspositionList(fAktivitaet, fAktualisiertStart, fAktualisiertEnd, fDatumStart, fDatumEnd, fDokumentart, fDokumentnummer, fDrucksache, fDrucksachetyp, fFrageNummer, fId, fPlenarprotokoll, fRessortFdf, fTitel, fUrheber, fVorgang, fVorgangstyp, fVorgangstypNotation, fWahlperiode, fZuordnung, cursor, format);
        // TODO: test validations
    }

}
