"""
Centralized path configuration for the Data Generation Pipeline.
"""

from pathlib import Path

# Base Paths
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_DIR = BASE_DIR / "data"
DATA_GENERATION_DIR = DATA_DIR / "dataGeneration"
DATA_FINAL_STAGE_DIR = DATA_DIR / "dataFinalStage"
DATA_EXCEL_DIR = DATA_DIR / "dataExcel"
BASE_CLASSIFICATION_DIR = BASE_DIR / "dataClassification"

# === Raw Data ===
RAW_DIR = DATA_GENERATION_DIR / "rawData"
RAW_ELECTORAL_TERMS = RAW_DIR / "electoralTerms" / "electoralTerms.csv"
RAW_XML_19 = RAW_DIR / "rawData19xml"
RAW_XML_20 = RAW_DIR / "rawData20xml"

# === Stage 03 ===
STAGE03 = DATA_GENERATION_DIR / "dataStage03"
FACTIONS_ABBR_STAGE03 = STAGE03 / "dataFactionsStage03" / "factionsAbbreviations.pkl"
SPEAKER_LOOKUP_STAGE03 = STAGE03 / "dataPoliticiansStage03" / "speaker_faction_lookup.csv"

# === Stage 04 ===
STAGE04 = DATA_GENERATION_DIR / "dataStage04"
SPEECH_CONTENT_STAGE04 = STAGE04 / "speechContent"
CONTRIB_EXT_19 = STAGE04 / "contributionsExtended" / "electoral_term_19"
CONTRIB_EXT_20 = STAGE04 / "contributionsExtended" / "electoral_term_20"
CONTRIB_SIMPLIFIED = STAGE04 / "contributionsSimplified"
SPEECH_CONTENT_04_19 = SPEECH_CONTENT_STAGE04 / "electoral_term_19"
SPEECH_CONTENT_04_20 = SPEECH_CONTENT_STAGE04 / "electoral_term_20"

# === Final Stage ===
FINAL_STAGE = DATA_FINAL_STAGE_DIR
FINAL_CONTRIB_SIM_DIR = FINAL_STAGE / "contributionsSimplifiedFinalStage"
FINAL_CONTRIB_EXT_DIR = FINAL_STAGE / "contributionsExtendedFinalStage"
FINAL_SPEECH_CONTENT_DIR = FINAL_STAGE / "speechContentFinalStage"
FINAL_SPEECH_CONTENT_20 = FINAL_SPEECH_CONTENT_DIR / "speech_content_20.pkl"
FINAL_SPEECH_CONTENT_19 = FINAL_SPEECH_CONTENT_DIR / "speech_content_19.pkl"
FINAL_FACTIONS_ABBREVIATIONS = DATA_FINAL_STAGE_DIR / "factionsAbbreviations.pkl"
FINAL_CONTRIB_SIM_19 = FINAL_CONTRIB_SIM_DIR / "contributions_simplified_19.pkl"
FINAL_CONTRIB_SIM_20 = FINAL_CONTRIB_SIM_DIR / "contributions_simplified_20.pkl"

# === Excel Exports ===
EXCEL_FINAL_STAGE = DATA_EXCEL_DIR / "finalStage"
DATA_EXCEL_GENERATOR_DIR = DATA_EXCEL_DIR / "dataGeneration"
EXCEL_MGS = DATA_EXCEL_GENERATOR_DIR / "mgs_wiki_rawData.xlsx"
EXCEL_MPS_STAGE02 = DATA_EXCEL_GENERATOR_DIR / "mps_stage02.xlsx"
EXCEL_MPS_STAGE03 = DATA_EXCEL_GENERATOR_DIR / "mpsFactions_stage03.xlsx"
EXCEL_POLITICIANS_STAGE03 = DATA_EXCEL_GENERATOR_DIR / "politicians_stage03.xlsx"
EXCEL_SPEECH_STAGE04_19 = DATA_EXCEL_GENERATOR_DIR / "speech_content_19_stage04.xlsx"
EXCEL_SPEECH_STAGE04_20 = DATA_EXCEL_GENERATOR_DIR / "speech_content_20_stage04.xlsx"
EXCEL_FACTIONS_STAGE02 = DATA_EXCEL_GENERATOR_DIR / "factions_stage02.xlsx"
EXCEL_FACTIONS_ABBR_STAGE03 = EXCEL_FINAL_STAGE/ "factionsAbbreviations.xlsx"
EXCEL_CONTRIB_SIMPLIFIED_STAGE04 = DATA_EXCEL_GENERATOR_DIR / "contributionsSimplified_stage04.xlsx"

# === Model Outputs ===
BASE_MODEL_OUTPUT_DIR = BASE_CLASSIFICATION_DIR / "modelOutput"
BASE_MODEL_LOG_DIR = BASE_MODEL_OUTPUT_DIR / "modelLogs"
BASE_MODEL_DIR = BASE_DIR / "classificationModels"

PREPROCESSING_EXPERIMENT_BERT = BASE_MODEL_DIR / "preprocessingExperimentBert"

# === Classification Datasets ===
BASE_CLASSIFICATION_DIR = DATA_DIR / "dataClassification"
BASE_CLASSIFICATION_DATASET_DIR = BASE_CLASSIFICATION_DIR / "dataSets"
CLASSIFICATION_SHORTENED_DATASET_DIR = BASE_CLASSIFICATION_DATASET_DIR / "dataSetsShortened"

BASE_CLASSIFICATION_DATASET_1_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_1_20.pkl"
BASE_CLASSIFICATION_DATASET_2_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_2_20.pkl"
BASE_CLASSIFICATION_DATASET_3_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_3_20.pkl"
BASE_CLASSIFICATION_DATASET_4_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_4_20.pkl"
BASE_CLASSIFICATION_DATASET_5_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_5_20.pkl"
BASE_CLASSIFICATION_DATASET_6_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_6_20.pkl"
BASE_CLASSIFICATION_DATASET_7_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_7_20.pkl"
BASE_CLASSIFICATION_DATASET_8_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_8_20.pkl"
BASE_CLASSIFICATION_DATASET_9_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_9_20.pkl"

BASE_CLASSIFICATION_DATASET_1_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_1_19.pkl"
BASE_CLASSIFICATION_DATASET_2_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_2_19.pkl"
BASE_CLASSIFICATION_DATASET_3_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_3_19.pkl"
BASE_CLASSIFICATION_DATASET_4_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_4_19.pkl"
BASE_CLASSIFICATION_DATASET_5_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_5_19.pkl"
BASE_CLASSIFICATION_DATASET_6_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_6_19.pkl"
BASE_CLASSIFICATION_DATASET_7_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_7_19.pkl"
BASE_CLASSIFICATION_DATASET_8_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_8_19.pkl"
BASE_CLASSIFICATION_DATASET_9_19 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_9_19.pkl"

BASE_CLASSIFICATION_DATASET_1_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_1_19_20.pkl"
BASE_CLASSIFICATION_DATASET_2_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_2_19_20.pkl"
BASE_CLASSIFICATION_DATASET_3_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_3_19_20.pkl"
BASE_CLASSIFICATION_DATASET_4_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_4_19_20.pkl"
BASE_CLASSIFICATION_DATASET_5_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_5_19_20.pkl"
BASE_CLASSIFICATION_DATASET_6_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_6_19_20.pkl"
BASE_CLASSIFICATION_DATASET_7_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_7_19_20.pkl"
BASE_CLASSIFICATION_DATASET_8_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_8_19_20.pkl"
BASE_CLASSIFICATION_DATASET_9_19_20 = BASE_CLASSIFICATION_DATASET_DIR / "data_set_9_19_20.pkl"

SAMPLED_IDS = BASE_CLASSIFICATION_DATASET_DIR / "sampled_ids.pkl"
TRAIN_IDS = BASE_CLASSIFICATION_DATASET_DIR / "train_ids.pkl"
TEST_IDS = BASE_CLASSIFICATION_DATASET_DIR / "test_ids.pkl"
TEST_BERT_IDS = BASE_CLASSIFICATION_DATASET_DIR / "test_bert_ids.pkl"
EVAL_BERT_IDS = BASE_CLASSIFICATION_DATASET_DIR / "eval_bert_ids.pkl"